update workflow

diff --git a/.github/workflows/test-coverage.yaml b/.github/workflows/test-coverage.yaml
--- a/.github/workflows/test-coverage.yaml
+++ b/.github/workflows/test-coverage.yaml
@@ -39,6 +39,9 @@ jobs:
               with:
                   node-version: '18'
 
+           - name: Install jq
+              run: sudo apt-get install -y jq
+
             - name: Create logs folder
               run: mkdir -p ./logs
 
@@ -49,9 +52,19 @@ jobs:
               run: npm run test:all
 
             - name: Check Coverage and Send Email If Below 100%
-              run: |
-                  COVERAGE=$(cat ./coverage/summary.txt | grep 'All files' | awk '{print $(NF-1)}')
-                  if [ "$COVERAGE" != "100%" ]; then
-                    echo "Coverage is below 100%. Sending an email..."
-                    # 여기에 이메일을 보내는 스크립트를 추가할 수 있습니다.
-                  fi
+              run:  |
+                    COVERAGE_LINES=$(jq '.total.lines.pct' ./coverage/coverage-summary.json)
+                    COVERAGE_STATEMENTS=$(jq '.total.statements.pct' ./coverage/coverage-summary.json)
+                    COVERAGE_FUNCTIONS=$(jq '.total.functions.pct' ./coverage/coverage-summary.json)
+                    COVERAGE_BRANCHES=$(jq '.total.branches.pct' ./coverage/coverage-summary.json)
+                    COVERAGE_BRANCHES_TRUE=$(jq '.total.branchesTrue.pct' ./coverage/coverage-summary.json)
+
+                    if (( $(echo "$COVERAGE_LINES < 100" | bc -l) )) || \
+                      (( $(echo "$COVERAGE_STATEMENTS < 100" | bc -l) )) || \
+                      (( $(echo "$COVERAGE_FUNCTIONS < 100" | bc -l) )) || \
+                      (( $(echo "$COVERAGE_BRANCHES < 100" | bc -l) )) || \
+                      (( $(echo "$COVERAGE_BRANCHES_TRUE < 100" | bc -l) )); then
+
+                      echo "One of the coverage metrics is below 100%, failing the workflow."
+                      exit 1
+                    fi
